### ISSUE TITLE
[BUG] Uncaught LinkError

### ISSUE THREAD

**Issue by Miaxos** [cloudflare/workers-rs#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of `workers-rs` are you using?

0.0.11

### Describe the bug

```
✘ [ERROR] Error on remote worker: ParseError: A request to the Cloudflare API
(/accounts/<AccountID>/workers/scripts/<scriptName>/edge-preview) failed.

      at throwFetchError (/Users/<someone>/.n/lib/node_modules/wrangler/wrangler-dist/cli.js:141293:17)
      at fetchResult (/Users/<someone>/.n/lib/node_modules/wrangler/wrangler-dist/cli.js:141262:5)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async createPreviewToken
  (/Users/<someone>/.n/lib/node_modules/wrangler/wrangler-dist/cli.js:141555:29)
      at async createWorkerPreview
  (/Users/<someone>/.n/lib/node_modules/wrangler/wrangler-dist/cli.js:141575:17)
      at async start (/Users/<someone>/.n/lib/node_modules/wrangler/wrangler-dist/cli.js:142271:34) {
    text: 'A request to the Cloudflare API
  (/accounts/<AccountID>/workers/scripts/<scriptName>/edge-preview) failed.',
    notes: [
      {
        text: 'Uncaught LinkError: WebAssembly.Instance(): Import #45 module="./index_bg.js"
  function="__wbg_clearTimeout_65417660fe82f08d" error: function import requires a callable\n' +
          '  at shim.js:135:16\n' +
          ' [code: 10021]'
      }
    ],
    location: undefined,
    kind: 'error',
    code: 10021
  }
```

### Steps To Reproduce

On macos (M1)

As soon as you use `clearTimeout` function.

```
use js_sys::Function;
use wasm_bindgen::prelude::*;
use wasm_bindgen::{JsCast, JsValue};

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_name = "setTimeout", catch)]
    fn set_timeout(handler: &Function, timeout: i32) -> std::result::Result<i32, JsValue>;

    #[wasm_bindgen(js_name = "setInterval", catch)]
    fn set_interval(handler: &Function, timeout: i32) -> std::result::Result<i32, JsValue>;

    #[wasm_bindgen(js_name = "clearTimeout")]
    fn clear_timeout(handle: i32);

    #[wasm_bindgen(js_name = "clearInterval")]
    fn clear_interval(handle: i32);
}
```

You create a timeout then clear it, the generated `shim.mjs` will have this line:

```
var __wbg_clearTimeout_412b3cc7b151def7 = typeof clearTimeout == "function" ? clearTimeout : notDefined("clearTimeout");
```

And it'll trigger the error

**Comment by Miaxos** [comment]
https://github.com/rustwasm/gloo/pull/249 gave me the answer, the issue was not linked to `worker-rs`.
