### ISSUE TITLE
[BUG] wrangler dev --test-scheduled throws exception when requesting __scheduled endpoint

### ISSUE THREAD

**Issue by zaytsev** [cloudflare/workers-rs#375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of `workers-rs` are you using?

0.0.18

### What version of `wrangler` are you using?

3.5.0

### Describe the bug

```
[mf:inf] Ready on http://127.0.0.1:8787/
✘ [ERROR] Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'scheduled')

  ${e.stack}`:_}function H(e,t,n,_){let s={a:e,b:t,cnt:1,dtor:n},f=(...c)=>{s.cnt++;let
  b=s.a;s.a=0;try{return
  _(b,s.b,...c)}finally{--s.cnt===0?r.__wbindgen_export_2.get(s.dtor)(b,s.b):s.a=b}};return
  f.original=s,f}function P(e,t,n){r.__wbindgen_export_3(e,t,i(n))}function D(e,t,n){let
  _=r.scheduled(i(e),i(t),i(n));return g(_)}function R(e,t,n){let _=r.fetch(i(e),i(t),i(n));return
  g(_)}function l(e,t){try{return e.apply(this,t)}catch(n){r.__wbindgen_export_4(i(n))}}function
  U(e,t,n,_){r.__wbindgen_export_5(e,t,i(n),i(_))}var
  V=Object.freeze({Off:0,0:"Off",Lossy:1,1:"Lossy",Lossless:2,2:"Lossless"}),B=Object.freeze({Error:0,0:"Error",Follow:1,1:"Follow",Manual:2,2:"Manual"}),A=class{__destroy_into_raw(){let
  t=this.__wbg_ptr;return this.__wbg_ptr=0,t}free(){let
  t=this.__destroy_into_raw();r.__wbg_intounderlyingbytesource_free(t)}get type(){let t,n;try{let
  f=r.__wbindgen_add_to_stack_pointer(-16);r.intounderlyingbytesource_type(f,this.__wbg_ptr);var
  _=u()[f/4+0],s=u()[f/4+1];return
  t=_,n=s,w(_,s)}finally{r.__wbindgen_add_to_stack_pointer(16),r.__wbindgen_export_6(t,n)}}get
  autoAllocateChunkSize(){return
  r.intounderlyingbytesource_autoAllocateChunkSize(this.__wbg_ptr)>>>0}start(t){r.intounderlyingbytesource_start(this.__wbg_ptr,i(t))}pull(t){let
  n=r.intounderlyingbytesource_pull(this.__wbg_ptr,i(t));return g(n)}cancel(){let
  t=this.__destroy_into_raw();r.intounderlyingbytesource_cancel(t)}},q=class{__destroy_into_raw(){let
  t=this.__wbg_ptr;return this.__wbg_ptr=0,t}free(){let
  t=this.__destroy_into_raw();r.__wbg_intounderlyingsink_free(t)}write(t){let
  n=r.intounderlyingsink_write(this.__wbg_ptr,i(t));return g(n)}close(){let
  t=this.__destroy_into_raw(),n=r.intounderlyingsink_close(t);return g(n)}abort(t){let
  n=this.__destroy_into_raw(),_=r.intounderlyingsink_abort(n,i(t));return
  g(_)}},M=class{__destroy_into_raw(){let t=this.__wbg_ptr;return this.__wbg_ptr=0,t}free(){let
  t=this.__destroy_into_raw();r.__wbg_intounderlyingsource_free(t)}pull(t){let
  n=r.intounderlyingsource_pull(this.__wbg_ptr,i(t));return g(n)}cancel(){let
  t=this.__destroy_into_raw();r.intounderlyingsource_cancel(t)}},L=class{__destroy_into_raw(){let
  t=this.__wbg_ptr;return this.__wbg_ptr=0,t}free(){let
  t=this.__destroy_into_raw();r.__wbg_minifyconfig_free(t)}get js(){return
  r.__wbg_get_minifyconfig_js(this.__wbg_ptr)!==0}set
  js(t){r.__wbg_set_minifyconfig_js(this.__wbg_ptr,t)}get html(){return
  r.__wbg_get_minifyconfig_html(this.__wbg_ptr)!==0}set
  html(t){r.__wbg_set_minifyconfig_html(this.__wbg_ptr,t)}get css(){return
  r.__wbg_get_minifyconfig_css(this.__wbg_ptr)!==0}set
  css(t){r.__wbg_set_minifyconfig_css(this.__wbg_ptr,t)}},C=class{__destroy_into_raw(){let
  t=this.__wbg_ptr;return this.__wbg_ptr=0,t}free(){let
  t=this.__destroy_into_raw();r.__wbg_pipeoptions_free(t)}get preventClose(){return
  r.pipeoptions_preventClose(this.__wbg_ptr)!==0}get preventCancel(){return
  r.pipeoptions_preventCancel(this.__wbg_ptr)!==0}get preventAbort(){return
  r.pipeoptions_preventAbort(this.__wbg_ptr)!==0}get signal(){let
  t=r.pipeoptions_signal(this.__wbg_ptr);return g(t)}},S=class{__destroy_into_raw(){let
  t=this.__wbg_ptr;return this.__wbg_ptr=0,t}free(){let
  t=this.__destroy_into_raw();r.__wbg_queuingstrategy_free(t)}get highWaterMark(){return
  r.queuingstrategy_highWaterMark(this.__wbg_ptr)}},v=class{__destroy_into_raw(){let
  t=this.__wbg_ptr;return this.__wbg_ptr=0,t}free(){let
  t=this.__destroy_into_raw();r.__wbg_r2range_free(t)}get offset(){try{let
  _=r.__wbindgen_add_to_stack_pointer(-16);r.__wbg_get_r2range_offset(_,this.__wbg_ptr);var
  t=u()[_/4+0],n=u()[_/4+1];return t===0?void
  0:n>>>0}finally{r.__wbindgen_add_to_stack_pointer(16)}}set
  offset(t){r.__wbg_set_r2range_offset(this.__wbg_ptr,!p(t),p(t)?0:t)}get length(){try{let
  _=r.__wbindgen_add_to_stack_pointer(-16);r.__wbg_get_r2range_length(_,this.__wbg_ptr);var
  t=u()[_/4+0],n=u()[_/4+1];return t===0?void
  0:n>>>0}finally{r.__wbindgen_add_to_stack_pointer(16)}}set
  length(t){r.__wbg_set_r2range_length(this.__wbg_ptr,!p(t),p(t)?0:t)}get suffix(){try{let
  _=r.__wbindgen_add_to_stack_pointer(-16);r.__wbg_get_r2range_suffix(_,this.__wbg_ptr);var
  t=u()[_/4+0],n=u()[_/4+1];return t===0?void
  0:n>>>0}finally{r.__wbindgen_add_to_stack_pointer(16)}}set
  suffix(t){r.__wbg_set_r2range_suffix(this.__wbg_ptr,!p(t),p(t)?0:t)}},$=class{__destroy_into_raw(){let
  t=this.__wbg_ptr;return this.__wbg_ptr=0,t}free(){let
  t=this.__destroy_into_raw();r.__wbg_readablestreamgetreaderoptions_free(t)}get mode(){let
  t=r.readablestreamgetreaderoptions_mode(this.__wbg_ptr);return g(t)}};function K(e,t){let
  n=o(t).cron,_=y(n,r.__wbindgen_export_0,r.__wbindgen_export_1),s=a;u()[e/4+1]=s,u()[e/4+0]=_}function
  X(e){return o(e).scheduledTime}function Y(e){g(e)}function Z(e,t){let n=w(e,t);return
  i(n)}function G(e){console.log(o(e))}function Q(){return l(function(e,t,n){let
  _=o(e).call(o(t),o(n));return i(_)},arguments)}function tt(e,t){let
  n=o(t).method,_=y(n,r.__wbindgen_export_0,r.__wbindgen_export_1),s=a;u()[e/4+1]=s,u()[e/4+0]=_}function
  et(e,t){let
  n=o(t).url,_=y(n,r.__wbindgen_export_0,r.__wbindgen_export_1),s=a;u()[e/4+1]=s,u()[e/4+0]=_}function
  nt(e){let t=o(e).headers;return i(t)}function rt(e){let t=o(e).cf;return p(t)?0:i(t)}function
  _t(){return l(function(){let e=new Headers;return i(e)},arguments)}function ot(){return
  l(function(e,t,n,_,s){o(e).set(w(t,n),w(_,s))},arguments)}function st(e,t){let n=o(t),_=typeof
  n=="string"?n:void 0;var
  s=p(_)?0:y(_,r.__wbindgen_export_0,r.__wbindgen_export_1),f=a;u()[e/4+1]=f,u()[e/4+0]=s}function
  it(e){let t;try{t=o(e)instanceof Error}catch{t=!1}return t}function ct(e){let
  t=o(e).toString();return i(t)}function ut(e){let t=o(e).cause;return i(t)}function ft(){return
  l(function(e,t){let n=new Response(o(e),o(t));return i(n)},arguments)}function bt(e){let t=new
  Uint8Array(e>>>0);return i(t)}function gt(){return l(function(e,t){let n=new
  Response(o(e),o(t));return i(n)},arguments)}function pt(){return l(function(e,t,n){let _=new
  Response(e===0?void 0:w(e,t),o(n));return i(_)},arguments)}function dt(e,t){try{var
  n={a:e,b:t},_=(f,c)=>{let b=n.a;n.a=0;try{return U(b,n.b,f,c)}finally{n.a=b}};let s=new
  Promise(_);return i(s)}finally{n.a=n.b=0}}function wt(e){return o(e).length}function at(){let
  e=r.memory;return i(e)}function lt(e){let t=o(e).buffer;return i(t)}function ht(e,t,n){let _=new
  Uint8Array(o(e),t>>>0,n>>>0);return i(_)}function yt(e,t,n){o(e).set(o(t),n>>>0)}function
  xt(e,t){let
  n=T(o(t)),_=y(n,r.__wbindgen_export_0,r.__wbindgen_export_1),s=a;u()[e/4+1]=s,u()[e/4+0]=_}function
  mt(e,t){throw new Error(w(e,t))}function kt(e){let t=Promise.resolve(o(e));return i(t)}function
  jt(e){let t=g(e).original;return t.cnt--==1?(t.a=0,!0):!1}function Et(e,t){let
  n=o(e).then(o(t));return i(n)}function Ot(e){let t=o(e).byobRequest;return p(t)?0:i(t)}function
  Tt(e,t){o(e).respond(t>>>0)}function At(e){let t=o(e).view;return p(t)?0:i(t)}function
  qt(e){return o(e).byteLength}function Mt(e){o(e).close()}function Lt(e,t){let n=new
  Error(w(e,t));return i(n)}function Ct(e){let t=o(e).buffer;return i(t)}function St(e){return
  o(e).byteOffset}function vt(e){o(e).close()}function $t(e,t){o(e).enqueue(o(t))}function Ft(e){let
  t=o(e);return i(t)}function Dt(e){console.error(o(e))}function Rt(){let e=new Object;return
  i(e)}function Wt(e){return i(e)}function zt(){return l(function(e,t,n){return
  Reflect.set(o(e),o(t),o(n))},arguments)}function Nt(e,t,n){let _=H(e,t,37,P);return i(_)}(void
  0)?.();var It={fetch:R,scheduled:D,queue:void 0};export{A as IntoUnderlyingByteSource,q as
  IntoUnderlyingSink,M as IntoUnderlyingSource,L as MinifyConfig,C as PipeOptions,V as
  PolishConfig,S as QueuingStrategy,v as R2Range,$ as ReadableStreamGetReaderOptions,B as
  RequestRedirect,Ct as __wbg_buffer_4e79326814bdd393,lt as __wbg_buffer_55ba7a6b1b92e2ac,Ot as
  __wbg_byobRequest_08c18cee35def1f4,qt as __wbg_byteLength_5299848ed3264181,St as
  __wbg_byteOffset_b69b0a07afccce19,Q as __wbg_call_587b30eea3e09332,ut as
  __wbg_cause_52959bcad93f9e0f,rt as __wbg_cf_703652f0d2c5b8d1,Mt as __wbg_close_da7e6fb9d9851e5a,vt
  as __wbg_close_e9110ca16e2567db,K as __wbg_cron_0c05433ef085704d,$t as
  __wbg_enqueue_d71a1a518e21f5c3,Dt as __wbg_error_a7e23606158b68b9,nt as
  __wbg_headers_1eff4f53324496e6,it as __wbg_instanceof_Error_fac23a8832b241da,wt as
  __wbg_length_0aab7ffd65ad19ed,G as __wbg_log_dc06ec929fc95a20,tt as
  __wbg_method_e15eb9cf1c32cdbb,_t as __wbg_new_143b41b4342650bb,dt as __wbg_new_2b55e405e4af4986,Rt
  as __wbg_new_2b6fea4ea03b1b95,Lt as __wbg_new_87297f22973157c8,ht as
  __wbg_newwithbyteoffsetandlength_88d1d8be5df94b9b,bt as __wbg_newwithlength_89eeca401d8918c2,gt as
  __wbg_newwithoptbuffersourceandinit_6c49960a834dd7cf,ft as
  __wbg_newwithoptreadablestreamandinit_d238e5b972c7b57f,pt as
  __wbg_newwithoptstrandinit_ff70839f3334d3aa,kt as __wbg_resolve_ae38ad63c43ff98b,Tt as
  __wbg_respond_8fadc5f5c9d95422,X as __wbg_scheduledTime_d9f7af363841929f,zt as
  __wbg_set_07da13cc24b69217,yt as __wbg_set_3698e3ca519b3c3c,ot as __wbg_set_76353df4722f4954,J as
  __wbg_set_wasm,Et as __wbg_then_8df675b8bb5d5e3c,ct as __wbg_toString_506566b763774a16,et as
  __wbg_url_3325e0ef088003ca,At as __wbg_view_231340b0dd8a2484,jt as __wbindgen_cb_drop,Nt as
  __wbindgen_closure_wrapper725,xt as __wbindgen_debug_string,at as __wbindgen_memory,Wt as
  __wbindgen_number_new,Ft as __wbindgen_object_clone_ref,Y as __wbindgen_object_drop_ref,st as
  __wbindgen_string_get,Z as __wbindgen_string_new,mt as __wbindgen_throw,It as default,R as fetch,D
  as scheduled};
  
  ^
      at D (/home/user/workspace/worker-rs-scheduled/build/worker/shim.mjs:2:290)
      at __facade_modules_dispatch__
  (/tmp/nix-shell.rwoumS/tmp-3476070-KLKkwSuK7Ygf/middleware-loader.entry.ts:110:19)
      at scheduled
  (/nix/store/9bcnx380wk8mflzn6lkmbhnpnhip7ii9-wrangler-3.5.0/lib/node_modules/wrangler/templates/middleware/middleware-scheduled.ts:8:22)
      at __facade_invokeChain__
  (/nix/store/9bcnx380wk8mflzn6lkmbhnpnhip7ii9-wrangler-3.5.0/lib/node_modules/wrangler/templates/middleware/common.ts:53:8)
      at __facade_invoke__
  (/nix/store/9bcnx380wk8mflzn6lkmbhnpnhip7ii9-wrangler-3.5.0/lib/node_modules/wrangler/templates/middleware/common.ts:63:8)
      at fetch (/tmp/nix-shell.rwoumS/tmp-3476070-KLKkwSuK7Ygf/middleware-loader.entry.ts:114:10)


✘ [ERROR] Uncaught (in response) TypeError: Cannot read properties of undefined (reading 'scheduled')
```

```
$ wasm-pack --version
wasm-pack 0.12.1
```

```
$ wasm-bindgen --version
wasm-bindgen 0.2.87
```

```
$ esbuild --version
0.19.1
```

The issue only reproduced on Linux machine (NixOS). Mac build is fine.
Downgrading `worker` to 0.0.17 also fixes the issue.
 
Example project https://github.com/zaytsev/workers-rs-scheduled

`build/worker/shim.mjs` with `worker` version = 0.0.18
```
 var n;function K(e){n=e}var d=new Array(128).fill(void 0)
```
`build/worker/shim.mjs` with `worker` version = 0.0.17
```
 var H=Object.defineProperty;var J=(e,t)=>{for(var r in t)H(e,r,{get:t[r],enumerable:!0})};
```

**Comment by zaytsev** [comment]
The issue resolved after upgrading worker-builder to 0.0.18
